/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "sda_aliases.h"
#include "sda.h"
#include "scl_aliases.h"
#include "scl.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "STEP_2a_aliases.h"
#include "STEP_2a.h"
#include "STEP_1a_aliases.h"
#include "STEP_1a.h"
#include "STEP_1b_aliases.h"
#include "STEP_1b.h"
#include "STEP_2b_aliases.h"
#include "STEP_2b.h"
#include "UART_USB.h"
#include "UART_USB_RX_ISR.h"
#include "COLOR_SENSOR_LED_aliases.h"
#include "COLOR_SENSOR_LED.h"
#include "UART_PI.h"
#include "UART_PI_RX_ISR.h"
#include "PUMP_1_aliases.h"
#include "PUMP_1.h"
#include "PUMP_2_aliases.h"
#include "PUMP_2.h"
#include "PUMP_3_aliases.h"
#include "PUMP_3.h"
#include "PUMP_4_aliases.h"
#include "PUMP_4.h"
#include "PUMP_5_aliases.h"
#include "PUMP_5.h"
#include "PUMP_6_aliases.h"
#include "PUMP_6.h"
#include "WEIGHT_ADC.h"
#include "WEIGHT_ADC_Pin_aliases.h"
#include "WEIGHT_ADC_Pin.h"
#include "UART_USB_IntClock.h"
#include "UART_PI_IntClock.h"
#include "WEIGHT_ADC_IRQ.h"
#include "WEIGHT_ADC_theACLK.h"
#include "WEIGHT_ADC_ExtVref_aliases.h"
#include "WEIGHT_ADC_ExtVref.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

